/**
 * MAD - OpenAPI 3.0
 * MAD(Mensch ärger dich nicht! aber in cool!) is a funny family game for one to four people.  Some useful links:  - [Spielregeln PDF](https://www.schmidtspiele.de/files/Produkte/4/49085%20-%20Mensch%20ärgere%20Dich%20nicht®/Mensch_aergere_dich_nicht49085D.pdf)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Figure model module.
 * @module model/Figure
 * @version 0.0.4
 */
class Figure {
    /**
     * Constructs a new <code>Figure</code>.
     * a playing figure
     * @alias module:model/Figure
     */
    constructor() { 
        
        Figure.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Figure</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Figure} obj Optional instance to populate.
     * @return {module:model/Figure} The populated <code>Figure</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Figure();

            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'Number');
            }
            if (data.hasOwnProperty('playerId')) {
                obj['playerId'] = ApiClient.convertToType(data['playerId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Figure</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Figure</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * a color
 * @member {Number} color
 */
Figure.prototype['color'] = undefined;

/**
 * unic player ID
 * @member {Number} playerId
 */
Figure.prototype['playerId'] = undefined;






export default Figure;

