/**
 * MAD - OpenAPI 3.0
 * MAD(Mensch ärger dich nicht! aber in cool!) is a funny family game for one to four people.  Some useful links:  - [Spielregeln PDF](https://www.schmidtspiele.de/files/Produkte/4/49085%20-%20Mensch%20ärgere%20Dich%20nicht®/Mensch_aergere_dich_nicht49085D.pdf)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Player from './Player';

/**
 * The GameEnds model module.
 * @module model/GameEnds
 * @version 0.0.4
 */
class GameEnds {
    /**
     * Constructs a new <code>GameEnds</code>.
     * who has won the game
     * @alias module:model/GameEnds
     */
    constructor() { 
        
        GameEnds.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GameEnds</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameEnds} obj Optional instance to populate.
     * @return {module:model/GameEnds} The populated <code>GameEnds</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameEnds();

            if (data.hasOwnProperty('hasEnded')) {
                obj['hasEnded'] = ApiClient.convertToType(data['hasEnded'], 'Boolean');
            }
            if (data.hasOwnProperty('Player')) {
                obj['Player'] = Player.constructFromObject(data['Player']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GameEnds</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GameEnds</code>.
     */
    static validateJSON(data) {
        // validate the optional field `Player`
        if (data['Player']) { // data not null
          Player.validateJSON(data['Player']);
        }

        return true;
    }


}



/**
 * game has hasEnded
 * @member {Boolean} hasEnded
 */
GameEnds.prototype['hasEnded'] = undefined;

/**
 * @member {module:model/Player} Player
 */
GameEnds.prototype['Player'] = undefined;






export default GameEnds;

