/**
 * MAD - OpenAPI 3.0
 * MAD(Mensch ärger dich nicht! aber in cool!) is a funny family game for one to four people.  Some useful links:  - [Spielregeln PDF](https://www.schmidtspiele.de/files/Produkte/4/49085%20-%20Mensch%20ärgere%20Dich%20nicht®/Mensch_aergere_dich_nicht49085D.pdf)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Player from './Player';

/**
 * The JoinUpdateResponse model module.
 * @module model/JoinUpdateResponse
 * @version 0.0.4
 */
class JoinUpdateResponse {
    /**
     * Constructs a new <code>JoinUpdateResponse</code>.
     * which players have joined and have all player joined
     * @alias module:model/JoinUpdateResponse
     */
    constructor() { 
        
        JoinUpdateResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JoinUpdateResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JoinUpdateResponse} obj Optional instance to populate.
     * @return {module:model/JoinUpdateResponse} The populated <code>JoinUpdateResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JoinUpdateResponse();

            if (data.hasOwnProperty('playerList')) {
                obj['playerList'] = ApiClient.convertToType(data['playerList'], [Player]);
            }
            if (data.hasOwnProperty('playerListFull')) {
                obj['playerListFull'] = ApiClient.convertToType(data['playerListFull'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JoinUpdateResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JoinUpdateResponse</code>.
     */
    static validateJSON(data) {
        if (data['playerList']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['playerList'])) {
                throw new Error("Expected the field `playerList` to be an array in the JSON data but got " + data['playerList']);
            }
            // validate the optional field `playerList` (array)
            for (const item of data['playerList']) {
                Player.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * array of joined players
 * @member {Array.<module:model/Player>} playerList
 */
JoinUpdateResponse.prototype['playerList'] = undefined;

/**
 * is player list full
 * @member {Boolean} playerListFull
 */
JoinUpdateResponse.prototype['playerListFull'] = undefined;






export default JoinUpdateResponse;

